### ISSUE TITLE
pocketwatch-1.1.1+1.20 `RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'pocketwatch'!`

### ISSUE THREAD

**Issue by SettingDust** [Minenash/Pocketwatch#10]
https://github.com/Minenash/Pocketwatch/blob/1.19.3/src/main/java/com/minenash/pocketwatch/PocketwatchConfigModel.java#L20
`List.of` is `ImmutableCollections`
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'pocketwatch'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.UnsupportedOperationException
	at java.base@17.0.8/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base@17.0.8/java.util.ImmutableCollections$AbstractImmutableList.replaceAll(ImmutableCollections.java:259)
	at com.minenash.pocketwatch.Pocketwatch.onInitializeClient(Pocketwatch.java:30)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 9 more
```

**Comment by Minenash** [comment]
Hey, sorry for the very long delay, this has now been fixed
